build_path: /opt/phpmyadmin
myadmin_port: 80
myadmin_ssl_port: 443

container_ssl_path: "/etc/ssl"
container_cert_path: "{{ container_ssl_path }}/certs/apache.crt"
container_key_path: "{{ container_ssl_path }}/private/apache.key"
cert_volumes:
  - "{{ cert_path if cert_path is defined | default(false) else omit }}:{{ container_cert_path }}:rw"
  - "{{ key_path if key_path is defined | default(false) else omit }}:{{ container_key_path }}:rw"
