api_user: osu_apis
apis_home: /apis
keytool_files_path: "{{ apis_home }}/keytool_files"
backup_path: "{{ keytool_files_path }}/backup"
script_path: "{{ apis_home }}/gen-keytool-certs.sh"

key_country: US
key_state: Oregon
key_location: Corvallis
key_organization: Oregon State University
key_organization_unit: Enterprise Computing Services
key_dname: "CN={{ ansible_fqdn }}, OU={{ key_organization_unit }}, O={{ key_organization }}, L={{ key_location }}, S={{ key_state }}, C={{ key_country }}"
key_ext: "san=dns:{{ ansible_fqdn }},dns:{{ ansible_hostname }}"
key_alias: server
key_alg: RSA
key_size: "2048"
sig_alg: SHA256withRSA
key_validity: "365"

keystore_file: "{{ key_alias }}.keystore"
truststore_file: "{{ key_alias }}.truststore"
certificate_file: "{{ key_alias }}.pem"
private_key_file: "{{ key_alias }}.key"

pyopenssl_version: "16.2.0"
