---
  - name: "create shell scripts to script directory"
    template:
      src: "express-api/{{ item.script }}.j2"
      dest: "{{ api_home }}/{{ item.script }}"
      group: "{{ api_group }}"
      owner: "{{ api_user }}"
      mode: "{{ item.mode }}"
      force: yes
    with_items:
      - { script: "{{ jenkins_run_express_script }}", mode: "0754" }
      - { script: "{{ start_express_container_script }}", mode: "0554" }

  - name: "check if line present in sudoers file"
    lineinfile:
      path: /etc/sudoers
      line: "{{ api_user }} ALL=(ALL) NOPASSWD: {{ start_express_container_path }}"
    register: content_has_line
    check_mode: yes

  - name: "add new lines to sudoers file"
    lineinfile:
      path: /etc/sudoers
      insertafter: "{{ disable_requiretty_for_api_user }}"
      line: "{{ api_user }} ALL=(ALL) NOPASSWD: {{ start_express_container_path }}"
    when: content_has_line is changed
