---
  - name: "copy script to script directory"
    copy:
      src: "express-api/{{ start_express_container_script }}"
      dest: "{{ start_express_container_path }}"
      group: "{{ api_group }}"
      owner: "{{ api_user }}"
      mode: "0554"
      force: yes

  - name: "create shell scripts to script directory"
    template:
      src: "express-api/{{ jenkins_run_express_script }}.j2"
      dest: "{{ api_home }}/{{ jenkins_run_express_script }}"
      group: "{{ api_group }}"
      owner: "{{ api_user }}"
      mode: "0754"
      force: yes

  - name: "check if line present in sudoers file"
    lineinfile:
      path: /etc/sudoers
      line: "{{ api_user }} ALL=(ALL) NOPASSWD: {{ start_express_container_path }}"
    register: content_has_line
    check_mode: yes

  - name: "add new lines to sudoers file"
    lineinfile:
      path: /etc/sudoers
      insertafter: "{{ disable_requiretty_for_api_user }}"
      line: "{{ api_user }} ALL=(ALL) NOPASSWD: {{ start_express_container_path }}"
    when: content_has_line is changed
