---
  - name: start mysql container
    docker_container:
      name: mysql-db
      image: "mysql:5.7"
      restart_policy: always
      env:
        MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      volumes:
        - "/var/lib/mysql:/var/lib/mysql"
      network_mode: host
