---
# variables for generic api
api_user: "osu_apis"
api_group: "apis"
api_home: "/apis"

# DO NOT put plaintext passwords in your playbook or host_vars; instead, use
# Using Vault in playbooks(https://docs.ansible.com/ansible/latest/user_guide/playbooks_vault.html)
# to encrypt sensitive data.
# api_user_password: ""

disable_requiretty_for_api_user: "Defaults:{{ api_user }} !requiretty"

# variables shared by all apis
jenkins_restart_script: "jenkins-restart.sh"
jenkins_restart_path: "{{ api_home }}/{{ jenkins_restart_script }}"
restart_container_script: "restart-container.sh"
restart_container_path: "{{ api_home }}/{{ restart_container_script }}"
container_health_interval_seconds: 60
container_health_timeout_seconds: 30
container_timeout_seconds: 60

# variables for dropwizard api
dropwizard_api: false
start_dropwizard_container_path: "{{ api_home }}/start-container.sh"
dropwizard_docker_image: "openjdk8-america-los-angeles"

# variables for express api
express_api: false
jenkins_run_express_script: "jenkins-run-express.sh"
start_express_container_script: "start-express-container.sh"
start_express_container_path: "{{ api_home }}/{{ start_express_container_script }}"
express_api_docker_path: "/opt/docker/express-api"
pm2_config: "pm2.yaml"
pm2_config_path: "{{ api_home }}/{{ pm2_config }}"
gulp_cli_version: "^2.2.0"
oracle_release: 19
oracle_update: 5
node_version: "10.17"
