---
  - name: "create shell scripts to script directory"
    template:
      src: "{{ item.script }}.j2"
      dest: "{{ api_home }}/{{ item.script }}"
      group: "{{ api_group }}"
      owner: "{{ api_user }}"
      mode: "{{ item.mode }}"
      force: yes
    with_items:
      - { script: "{{ jenkins_run_express_script }}", mode: "0754" }
      - { script: "{{ start_express_container_script }}", mode: "0554" }

  - name: "add new lines to sudoers file"
    lineinfile:
      dest: /etc/sudoers
      insertafter: '## Allow root to run any commands anywhere'
      line: "{{ item }}"
    with_items:
      - "Defaults:{{ api_user }} !requiretty"
      - "{{ api_user }} ALL=(ALL) NOPASSWD: {{ api_home }}/{{ start_express_container_script }}"
