---
  - name: "copy script to script directory"
    copy:
      src: "{{ start_express_container_script }}"
      dest: "{{ api_home }}/{{ start_express_container_script }}"
      group: "{{ api_group }}"
      owner: "{{ api_user }}"
      mode: "0554"
      force: yes

  - name: "create shell scripts to script directory"
    template:
      src: "{{ jenkins_run_express_script }}.j2"
      dest: "{{ api_home }}/{{ jenkins_run_express_script }}"
      group: "{{ api_group }}"
      owner: "{{ api_user }}"
      mode: "0754"
      force: yes

  - name: "add new lines to sudoers file"
    lineinfile:
      dest: /etc/sudoers
      insertafter: '## Allow root to run any commands anywhere'
      line: "{{ item }}"
    with_items:
      - "Defaults:{{ api_user }} !requiretty"
      - "{{ api_user }} ALL=(ALL) NOPASSWD: {{ api_home }}/{{ start_express_container_script }}"
