---
  - name: add EPEL repository (CentOS)
    yum:
      name: epel-release
    when: ansible_distribution == "CentOS"

  - name: install pip (CentOS)
    yum:
      name: python-pip
      state: installed
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: install pip (Debian)
    apt:
      name: python-pip
      update_cache: yes
    when: ansible_distribution == 'Debian'

  - name: install pip (Ubuntu)
    apt:
      name: python3-pip
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: update pip and pip packages
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      extra_args: --ignore-installed
    with_items:
      - { name: pip, version: "{{ pip_version }}"}
      - { name: requests, version: "{{ requests_version }}"}
      - { name: pyOpenSSL, version: "{{ pyopenssl_version }}"}
