---
  - name: add EPEL repository (CentOS)
    yum:
      name: epel-release
    when: ansible_distribution == "CentOS"

  - name: install pip (CentOS)
    yum:
      name: python-pip
      state: installed
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: install pip (Debian)
    apt:
      name: python-pip
      update_cache: yes
    when: ansible_distribution == 'Debian'

  - name: update pip to latest
    pip:
      name: pip
      version: "{{ pip_version }}"

  - name: update pyOpenSSL
    pip:
      name: pyOpenSSL
      version: "{{ pyopenssl_version }}"
