---
  - name: install mysql client
    yum:
      name: mysql
      state: present
    when: ansible_distribution == 'CentOS'

  - name: install mysql client
    apt:
      name: default-mysql-client
      state: present
    when: ansible_distribution == 'Debian'
