---
  - name: check Python 3 version
    command: "python3 --version"
    register: python_3_installed_version
    failed_when: false
    changed_when: false

  - name: install Python 3
    include_tasks: install.yml
    when: python_3_installed_version.rc != 0 or python_3_installed_version.stdout != python_3_version_output

  - name: add python3 as priority alternate
    shell:
      cmd: "update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1 && update-alternatives --install /usr/bin/python python /usr/bin/python3 2"
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
