---
  # Set up user and group

  - name: create group apis
    group:
      name: apis
      state: present

  - name: check if modify user password or not
    fail:
      msg: "Please enter a new password for {{ user }}!"
    when: user_password == ""

  - name: create user "{{ user }}"
    user:
      name: "{{ user }}"
      comment: "OSU APIs"
      group: apis
      password: "{{ user_password }}"

  # Create directories

  - name: create apis directory structure
    file:
      path: '{{ item }}'
      state: directory
      group: apis
      owner: "{{ user }}"
      mode: 0770
    with_items:
      - /apis
      - /apis/apis
      - /apis/config

  - name: create /apis/keytool_files directory
    file:
      path: "{{ item }}"
      state: directory
      group: apis
      owner: "{{ user }}"
      mode: 0555
    with_items:
      - /apis/keytool_files
      - /apis/keytool_files/backup

  # Build docker image for api's
  
  - name: copy dockerfile
    copy:
      src: files/Dockerfile
      dest: /tmp/Dockerfile
      owner: root
      group: root
      mode: 0744

  - name: build docker image
    docker_image:
      path: /tmp
      name: "{{ docker_image }}"

  - name: delete dockerfile
    file:
      state: absent
      path: /tmp/Dockerfile
      
  # Copy scripts

  - name: copy wrapper script
    template:
      src: files/jenkins-run.j2
      dest: /apis/jenkins-run.sh
      group: apis
      owner: "{{ user }}"
      mode: 0754
      force: yes

  - name: copy script
    template:
      src: files/start-container.j2
      dest: "{{ script_path }}"
      group: apis
      owner: "{{ user }}"
      mode: 0554
      force: yes

  # Add lines to sudoers file so jenkins can run the scripts
  # This also prevents adding apis user to the docker group

  - name: add new lines to sudoers file
    lineinfile:
      dest: /etc/sudoers
      insertafter: '## Allow root to run any commands anywhere'
      line: "{{ item }}"
    with_items:
      - "Defaults:{{ user}} !requiretty"
      - "{{ user }} ALL=(ALL) NOPASSWD: {{ script_path }}"
