---
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
  - name: set vm.max_map_count
    command: sysctl -w vm.max_map_count=262144

  - name: start elasticsearch container
    docker_container:
      name: elasticsearch
      image: "docker.elastic.co/elasticsearch/elasticsearch:{{ es_version }}"
      restart_policy: always
      network_mode: host
      env:
        bootstrap.memory_lock: "true"
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      ulimits:
        - memlock:-1:-1
      volumes:
        - /usr/share/elasticsearch/data

  - name: download templates from locations-api
    get_url:
      url: "{{ locations_api_raw_url }}{{ locations_api_branch }}/{{ item }}"
      dest: "/tmp/{{ item }}"
    with_items:
      - "{{ locations_template_filename }}"
      - "{{ services_template_filename }}"

  - name: POST templates to elasticsearch
    command: >
      curl -H \"Content-Type: application/json\"
      -XPOST http://localhost:9200/_template/template_{{ item.template_num }}
      --data-binary \"@/tmp/{{ item.filename }}\"
    args:
      warn: no
    with_items:
      - { filename: "{{ locations_template_filename }}", template_num: "1" }
      - { filename: "{{ services_template_filename }}", template_num: "2" }

  - name: clean up template files
    file:
      path: /tmp/{{ item }}
      state: absent
    with_items:
      - "{{ locations_template_filename }}"
      - "{{ services_template_filename }}"
