---
  - name: start elasticsearch container
    docker_container:
      name: elasticsearch
      image: "docker.elastic.co/elasticsearch/elasticsearch:{{ es_version }}"
      restart_policy: always
      network_mode: host
