---
- name: set variables for debian
  set_fact:
    apt_repo: "{{ debian_apt_repo }}"
    docker_ce_version: "{{ debian_docker_ce_version }}"
  when: 'ansible_distribution == "Debian"'

- name: set variables for ubuntu
  set_fact:
    apt_repo: "{{ ubuntu_apt_repo }}"
    docker_ce_version: "{{ ubuntu_docker_ce_version }}"
  when: 'ansible_distribution == "Ubuntu"'

- name: ensure old versions of Docker are not present
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: true

- name: add docker key
  apt_key:
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    data: "{{ lookup('file', 'docker.gpg') }}"
    state: present

- name: add docker repo
  apt_repository:
    repo: 'deb [arch=amd64] {{ apt_repo }} {{ ansible_distribution_release }} stable'
    filename: docker
    state: present
    update_cache: true

- name: install docker
  apt:
    name: '{{ docker_ce_pkg_name }}={{ docker_ce_version }}'
    state: present
    update_cache: true

- name: Pin docker version
  copy:
    dest: /etc/apt/preferences.d/{{ docker_ce_pkg_name }}
    content: |
      Package: {{ docker_ce_pkg_name }}
      Pin: version {{ docker_ce_version }}
      Pin-Priority: 1002
