---
- name: ensure old versions of Docker are not present
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: true

- name: add docker key
  apt_key:
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    data: "{{ lookup('file', 'docker.gpg') }}"
    state: present

- name: add docker repo
  apt_repository:
    repo: 'deb [arch=amd64] {{debian_apt_repo}} {{ansible_distribution_release}} stable'
    filename: docker
    state: present
    update_cache: true

- name: install docker
  apt:
    name: 'docker-ce={{debian_docker_version}}'
    state: present
    update_cache: true

- name: enable docker service
  service:
    name: docker
    enabled: yes
    state: started
