---

- name: CentOS
  include: centos.yml
  when: 'ansible_distribution == "CentOS"'

- name: apt-get
  include: apt.yml
  when: 'ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"'

- name: OracleLinux
  include: oraclelinux.yml
  when: 'ansible_distribution == "OracleLinux"'

- name: create /etc/docker directory
  file:
    path: /etc/docker
    state: directory
    mode: 0644

- name: copy logging driver configuration
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: "restart Docker"

- name: enable docker service
  service:
    name: docker
    enabled: yes
    state: started

# Install docker-compose which also installs the docker python library required by some ansible docker modules
- name: install docker-compose
  pip:
    name: docker-compose
    state: present
  when: ansible_distribution != 'OracleLinux'
