---

- name: CentOS
  include: centos.yml
  when: 'ansible_distribution == "CentOS"'

- name: apt-get
  include: apt.yml
  when: 'ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"'

- name: create /etc/docker directory
  file:
    path: /etc/docker
    state: directory
    mode: 0644

- name: copy logging driver configuration
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: "restart Docker"

- name: enable docker service
  service:
    name: docker
    enabled: yes
    state: started

# Install docker-compose which also installs the docker python library required by some ansible docker modules
- name: install docker-compose
  pip:
    executable: pip3
    name: docker-compose
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Ansible docker modules sometimes forcibly uses python2, install docker-py for that case
- name: install docker with pip2 (Debian)
  pip:
    executable: pip2
    name:
      - docker
    state: present
  when: ansible_distribution == 'Debian'

# Ansible docker modules are forcibly using python3.6 so install docker-compose for that
- name: install docker-compose with python3 used by ansible_docker (Ubuntu)
  shell:
    cmd: /usr/bin/python3.6 -m pip install docker-compose
  when: ansible_distribution == 'Ubuntu'

# CentOS is using python2 and must use docker instead of docker-compose
- name: install docker with pip (CentOS)
  pip:
    name: docker
  when: ansible_distribution == 'CentOS'
