---
- name: "create docker garbage collection directories"
  file:
    path: "{{garbage_home}}/{{backup_images_dir}}"
    state: "directory"
    owner: "{{garbage_user}}"
    group: "{{garbage_group}}"
    mode: "0660"

- name: "create empty log file if no log exists"
  copy:
    content: ""
    dest: "{{garbage_home}}/{{log_file}}"
    force: no
    group: "{{garbage_group}}"
    owner: "{{garbage_user}}"
    mode: "0660"

- name: "generate all templated scripts"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{garbage_user}}"
    mode: "{{item.mode}}"
    force: yes
  with_items:
    - { src: "{{garbage_script}}.j2", dest: "{{garbage_home}}/{{garbage_script}}", mode: "0554"}
    - { src: "{{backup_removal_script}}.j2", dest: "{{garbage_home}}/{{backup_removal_script}}", mode: "0554"}
    - { src: "{{backup_permission_script}}.j2", dest: "{{garbage_home}}/{{backup_permission_script}}", mode: "0754"}

- name: "execute garbage collection script and backup removal permission scipt"
  command: "{{ item }}"
  with_items:
    - "{{garbage_home}}/{{garbage_script}}"
    - "{{garbage_home}}/{{backup_permission_script}}"
