---
- name: "create docker garbage collection directories"
  file:
    path: "{{garbage_home}}/{{backup_images_dir}}"
    state: "directory"
    owner: "{{garbage_user}}"
    group: "{{garbage_group}}"
    mode: "0754"

- name: "generate garbage collection script"
  template:
    src: "{{garbage_script}}.j2"
    dest: "{{garbage_home}}/{{garbage_script}}"
    owner: "{{garbage_user}}"
    mode: "0754"

- name: "execute garbage collection script"
  command: "{{garbage_home}}/{{garbage_script}}"
