---
  - name: install OpenJDK 8 (CentOS)
    yum:
      name: java-1.8.0-openjdk-devel
    when: ansible_distribution == 'CentOS'

  - name: configure apt to allow expired repos (Debian Jessie)
    lineinfile:
      path: /etc/apt/apt.conf
      regexp: '^Acquire::Check-Valid-Until'
      line: 'Acquire::Check-Valid-Until "0";'
      create: yes
    when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

  - name: add backports repo (Debian Jessie)
    apt_repository:
      repo: "{{ jessie_backports_repo }}"
      state: present
    when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

  - name: update ca-certificates-java (Debian Jessie)
    apt:
      name: ca-certificates-java
      default_release: jessie-backports
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'
    tags:
      - skip_ansible_lint

  - name: install OpenJDK 8 (Debian)
    apt:
      name: openjdk-8-jdk
      update_cache: yes
    when: ansible_distribution == 'Debian'

  # The repo's release file is expired which will cause errors when updating apt cache
  - name: remove backports repo (Debian Jessie)
    apt_repository:
      repo: "{{ jessie_backports_repo }}"
      state: absent
    when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

  - name: reconfigure apt to not allow expired repos (Debian Jessie)
    lineinfile:
      path: /etc/apt/apt.conf
      regexp: '^Acquire::Check-Valid-Until'
      state: absent
    when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'

  - name: set default java version
    alternatives:
      name: java
      path: "{{ java8_home }}/bin/java"
